---
# tasks file for deploy-docker-compose

- name: Set fact for local docker-compose.yml
  set_fact: local_docker_compose='{{ deploy_path }}docker-compose.yml'

- name: Set fact for remote_deploy_path
  set_fact: remote_deploy_path='{{ remote_deploy_base_path }}/{{ remote_deploy_name }}'

- name: Fail if no docker-compose.yml is present in project
  fail:
    msg: 'No docker-compose.yml found in {{ deploy_path }}'
  when: not (local_docker_compose is file)

- name: Copy project to remote host
  copy:
    src: '{{ deploy_path }}'
    dest: '{{ remote_deploy_path }}'

- name: Remove remote docker stack
  shell: docker-compose down {{ remote_remove_args }}
  args:
    chdir: '{{ remote_deploy_path }}'
  when: remote_remove_only

- name: Login in to remote docker registry
  shell: docker login -p {{ remote_docker_login_pass }} -u {{ remote_docker_login_user }} {{ remote_docker_login_registry }}
  when: remote_docker_login_pass is defined and remote_docker_login_user is defined and remote_remove_only != false

- name: Pull images from docker-compose remotely
  shell: docker-compose pull
  args:
    chdir: '{{ remote_deploy_path }}'
  when: remote_pull_images and remote_remove_only != false

- name: Start stack with docker-compose remotely
  shell: docker-compose up -d
  args:
    chdir: '{{ remote_deploy_path }}'
  when: remote_remove_only != false
